import type { EditorThemeClasses } from "lexical";

export const editorTheme: EditorThemeClasses = {
  paragraph: "mb-1 last:mb-0",
  heading: {
    h1: "text-2xl font-bold mb-2",
    h2: "text-xl font-semibold mb-2",
    h3: "text-lg font-medium mb-1",
  },
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    code: "font-mono text-sm bg-muted px-1.5 py-0.5 rounded",
  },
  list: {
    ul: "list-disc ml-4 mb-2",
    ol: "list-decimal ml-4 mb-2",
    listitem: "mb-0.5",
    nested: {
      listitem: "list-none",
    },
  },
  quote: "border-l-2 border-border pl-3 text-muted-foreground italic mb-2",
  code: "font-mono text-sm bg-muted rounded-md p-3 mb-2 block overflow-x-auto",
  codeHighlight: {
    atrule: "text-blue-600",
    attr: "text-blue-600",
    boolean: "text-orange-600",
    builtin: "text-teal-600",
    cdata: "text-muted-foreground",
    char: "text-green-600",
    class: "text-teal-600",
    "class-name": "text-teal-600",
    comment: "text-muted-foreground",
    constant: "text-orange-600",
    deleted: "text-red-600",
    doctype: "text-muted-foreground",
    entity: "text-red-600",
    function: "text-blue-600",
    important: "text-orange-600",
    inserted: "text-green-600",
    keyword: "text-purple-600",
    namespace: "text-muted-foreground",
    number: "text-orange-600",
    operator: "text-foreground",
    prolog: "text-muted-foreground",
    property: "text-blue-600",
    punctuation: "text-muted-foreground",
    regex: "text-green-600",
    selector: "text-green-600",
    string: "text-green-600",
    symbol: "text-orange-600",
    tag: "text-red-600",
    url: "text-blue-600",
    variable: "text-red-600",
  },
  link: "text-primary underline cursor-pointer",
};
