/**
 * Simple Streaming Monitor — Multi-Tenant Example
 *
 * This file IS the program. The user writes only TypeScript.
 * The CLI sends this to the server, which evaluates it via GraalJS
 * and executes it on an embedded NATS JetStream backbone.
 *
 * Deploy in two namespaces to verify multi-tenant isolation:
 *   quarkctl system deploy -f system.quark.ts -n alice
 *   quarkctl system deploy -f system.quark.ts -n bob
 *
 * Type definitions are provided by quark.d.ts (generated by `quarkctl init`).
 * Place it in the same directory as this file for IDE autocomplete.
 */

export default {
    name: "monitor",
    namespace: "alice",

    nodes: {
        // A 1-second timer that publishes "tick" events.
        timer: {
            uses: "quark/time/schedule/timer:v1",
            interval: "1s",
            events: ["tick"],
        },

        // CPU profiler — triggered by timer ticks.
        cpu: {
            uses: "quark/system/cpu/profile:v1",
            timeout: "200ms",
            listens: ["timer.tick"],
            events: ["data"],
            onFailure: { retry: 3, routeTo: "writer" },
        },

        // Memory profiler — triggered by timer ticks.
        memory: {
            uses: "quark/system/memory/profile:v1",
            timeout: "200ms",
            listens: ["timer.tick"],
            events: ["data"],
            onFailure: { retry: 3, routeTo: "writer" },
        },

        // JSON file writer — appends each sample as a JSON Line.
        writer: {
            uses: "quark/io/file/write:v1",
            path: "./example/simple-streaming/json/system-monitor.jsonl",
            mode: "append",
            listens: ["cpu.data", "memory.data", "fallback.cpu", "fallback.memory"],
        },

        // Streaming endpoint — SSE server.
        stream: {
            uses: "quark/stream/sse/broadcast:v1",
            listens: ["cpu.data", "memory.data"],
        },
    },
};
